### ISSUE TITLE
鼠标右键关闭项目后，再无法创建新项目

### ISSUE THREAD

**Issue by qibo-cn** [lichang98/vscode_ext_web#2]
鼠标右键关闭当前项目后，点击
![image](https://user-images.githubusercontent.com/17426311/106832482-b91d5180-66cc-11eb-852c-a6c4ac90fb1c.png)

创建新项目，没反应， 
或者点
![image](https://user-images.githubusercontent.com/17426311/106832426-a014a080-66cc-11eb-8f74-413021051585.png)
中的创建项目后，弹出
![image](https://user-images.githubusercontent.com/17426311/106832357-73608900-66cc-11eb-9257-f5ac636af269.png)

**Comment by lichang98** [comment]
这里刚把功能移动到这里，还没调试确认

**Comment by lichang98** [comment]
该问题已处理
