### ISSUE TITLE
工程创建，和保存时，名字可以被设置为不一样的，不合理

### ISSUE THREAD

**Issue by qibo-cn** [lichang98/vscode_ext_web#4]
![image](https://user-images.githubusercontent.com/17426311/106836363-fa652f80-66d3-11eb-985d-c86c7b95cddf.png)

这里点右键“保存工程”，在弹出的保存对话框中，项目名是必填项。
而在创建工程时，
![image](https://user-images.githubusercontent.com/17426311/106836898-f2f25600-66d4-11eb-9476-a59b8f8a8076.png)
这里的项目名称是必填项。

这两处的名字存在用户写的不一致的可能。
建议在项目创建向导中提供保存路径选择，点“创建”及表示保存工程，冲突时提示用户修改保存路径，或者修改项目名称。
而工程右键的保存，仅做保存，保存成功后提示保存完成。

**Comment by lichang98** [comment]
这部分已经调整
